#pragma once
#include "simulation/aerodynamics/public/components/effector.hpp"
#include "simulation/aerodynamics/public/data/types.hpp"

#include <Eigen/Dense>
#include <string>
#include <vector>

namespace aerodynamics
{

	struct Surface {
		std::string id;
		double chord;
		double span;
		double area;
		double AR;
		// For a thin airfoil in incompressible subsonic flow, the aerodynamic center is approximately at the quarter chord
		Eigen::Vector3d pB_acB;
		Eigen::Vector3d n;
		double CL0, e, i, CD0, CDa, a0, CM0, CMa;
		DynamicDerivatives dyn;
		std::vector<SurfaceEffector> effectors;

		/**
		 * @brief Computes the surface area and aspect ratio from the chord and span.
		 */
		void compute_geometry();

		/**
		 * @brief Computes the local aerodynamic kinematics at the surface.
		 *
		 * @tparam T Scalar type used for the computation.
		 * @param[in] input Body state, atmosphere, actuator inputs, and wind used for the surface calculation.
		 * @return Relative velocity [m/s], airspeed [m/s], dynamic pressure [Pa], angle of attack [rad], and
		 * normalized angular rates [-].
		 */
		template <typename T> SurfaceKinematics_T<T> compute_kinematics(const SurfaceInput_T<T>& input);

		/**
		 * @brief Computes the surface aerodynamic coefficients.
		 *
		 * @tparam T Scalar type used for the computation.
		 * @param[in] sk Surface aerodynamic kinematics.
		 * @param[in] u Surface-actuator inputs.
		 * @return Lift, drag, and pitching-moment coefficients [-].
		 */
		template <typename T>
		SurfaceCoefficients_T<T> compute_coefficients(const SurfaceKinematics_T<T>& sk,
			const actuators::SurfaceActuatorInputs_T<T>& u);

		/**
		 * @brief Computes the aerodynamic wrench generated by the surface.
		 *
		 * @tparam T Scalar type used for the computation.
		 * @param[in] pB_GB Body-expressed center-of-gravity position [m].
		 * @param[in] sk Surface aerodynamic kinematics.
		 * @param[in] sc Surface aerodynamic coefficients [-].
		 * @return Aerodynamic force [N] and moment [N m] about the center of gravity.
		 */
		template <typename T>
		dynamics::Wrench_T<T> compute_loads(const constants::Vector3_T<T>& pB_GB,
			const SurfaceKinematics_T<T>& sk,
			const SurfaceCoefficients_T<T>& sc);

		/**
		 * @brief Computes the aerodynamic wrench generated by the surface for one simulation step.
		 *
		 * @tparam T Scalar type used for the computation.
		 * @param[in] input Body state, atmosphere, actuator inputs, and wind used for the surface calculation.
		 * @return Aerodynamic force [N] and moment [N m] about the center of gravity.
		 */
		template <typename T> dynamics::Wrench_T<T> step(const SurfaceInput_T<T>& input);
	};

} // namespace aerodynamics

#include "simulation/aerodynamics/public/components/surface.tpp"
