#pragma once
#include "simulation/propulsion/public/data/types.hpp"

#include <Eigen/Dense>
#include <optional>

namespace propulsion
{

	struct PropulsorEffector {
		Eigen::Vector3d pB_propB = constants::Zero3;
		Eigen::Vector3d n_prop = constants::ei;
		std::optional<PropellerAssembly> propellers;
		std::optional<double> propeller_omega_t_1;

		/**
		 * @brief Adds propeller torque, inertial, and gyroscopic effects to a propulsive wrench.
		 *
		 * @tparam T Scalar type used for the propulsion calculation.
		 * @param[in] input Propulsor state, atmosphere, thrust, and timing data.
		 * @param[in] WB_propulsive Existing body-expressed propulsive force [N] and moment [N m].
		 * @param[in] n_prop_t Body-expressed propulsor axis unit vector [-].
		 * @return Updated propulsive wrench and calculated propeller angular velocity [rad/s].
		 */
		template <typename T>
		PropulsorEffectorOutput_T<T> compute_propeller_effects(const PropulsorEffectorInput_T<T>& input,
			dynamics::Wrench_T<T> WB_propulsive,
			const constants::Vector3_T<T>& n_prop_t);

		/**
		 * @brief Computes the wrench generated by one propulsor.
		 *
		 * @tparam T Scalar type used for the propulsion calculation.
		 * @param[in] input Propulsor state, atmosphere, thrust, and timing data.
		 * @return Body-expressed propulsive force [N], moment [N m], and optional propeller angular velocity [rad/s].
		 */
		template <typename T> PropulsorEffectorOutput_T<T> step(const PropulsorEffectorInput_T<T>& input);

		/**
		 * @brief Commits the current propeller angular velocity as runtime state.
		 *
		 * @param[in] propeller_omega_t Current propeller angular velocity [rad/s], or no value when unavailable.
		 */
		void commit(const std::optional<double>& propeller_omega_t);
	};

} // namespace propulsion

#include "simulation/propulsion/public/components/effector.tpp"
